# Generated by Django 5.2 on 2025-04-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Food', 'Food'), ('Bills', 'Bills'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Others', 'Others')], max_length=100),
        ),
    ]
