# Generated by Django 5.2 on 2025-05-03 00:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_name_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=api.models.get_default_profile_picture, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='color',
            field=models.CharField(default='#84AE26', max_length=7),
        ),
    ]
