# Generated by Django 5.2 on 2025-05-03 06:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_profile_picture_wallet_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=api.models.get_default_profile_picture, null=True, upload_to=api.models.user_profile_picture_path),
        ),
    ]
