# Generated by Django 5.2 on 2025-05-03 15:02

from django.db import migrations

def add_builtin_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    built_in_categories = [
        "Food",
        "Transportation",
        "Entertainment",
        "Utilities",
        "Healthcare",
        "Education",
        "Shopping",
        "Savings",
        "Miscellaneous"
    ]
    for category_name in built_in_categories:
        Category.objects.get_or_create(name=category_name)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_wallet_balance'),
    ]

    operations = [
        migrations.RunPython(add_builtin_categories),
    ]
